// frontend-vue/src/App.vue
<script setup lang="ts">
import { ref, onMounted, provide } from 'vue'
import TopToolbar from './components/TopToolbar.vue'
import FileList from './components/FileList.vue'
import FloatingToolbar from './components/FloatingToolbar.vue'
import WorkflowCanvas from './components/WorkflowCanvas.vue'
import BottomPanel from './components/BottomPanel.vue'
import SaveDialog from './components/SaveDialog.vue'
import type { PluginDefinition, CategoryDefinition, LogEntry, Position } from './types/api'
import { getNodes, listWorkflows, getCategories, saveWorkflow, loadWorkflow as loadWorkflowApi, executeWorkflow } from './services/api'

interface NodeItem {
  id: string
  type: string
  position: Position
  data: any
}

interface EdgeItem {
  id: string
  source: string
  target: string
}

const plugins = ref<PluginDefinition[]>([])
const categories = ref<CategoryDefinition[]>([])
const workflowList = ref<string[]>([])
const currentWorkflow = ref<string | null>(null)
const logs = ref<LogEntry[]>([])
const nodes = ref<NodeItem[]>([])
const edges = ref<EdgeItem[]>([])
const selectedNodeId = ref<string | null>(null)
const showSaveDialog = ref(false)
const currentTaskId = ref<string | null>(null)

const addLog = (message: string, level: 'debug' | 'info' | 'warn' | 'error', source: 'FE' | 'BE' = 'FE') => {
  const entry: LogEntry = {
    id: `${Date.now()}_${Math.random().toString(36).slice(2, 11)}`,
    timestamp: new Date().toLocaleTimeString('zh-CN', {
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false
    }),
    source,
    level,
    message,
    nodeId: null
  }
  logs.value.push(entry)
}

const clearLogs = () => {
  logs.value = []
}

const handleAddNode = (data: { id: string }, position: Position) => {
  const id = `node_${Date.now()}`
  const plugin = plugins.value.find(p => p.id === data.id)
  if (!plugin) {
    addLog(`Plugin not found: ${data.id}`, 'error')
    return
  }

  const newNode: NodeItem = {
    id,
    type: 'dynamic',
    position,
    data: {
      ...plugin,
      configValues: plugin.config.reduce((acc: Record<string, unknown>, field: any) => {
        acc[field.key] = field.default
        return acc
      }, {})
    }
  }
  nodes.value.push(newNode)
  addLog(`Added node: ${plugin.name}`, 'info')
}

const handleSelectNode = (nodeId: string | null) => {
  selectedNodeId.value = nodeId
}

const handleDeleteNode = (nodeId: string) => {
  nodes.value = nodes.value.filter(n => n.id !== nodeId)
  edges.value = edges.value.filter(e => e.source !== nodeId && e.target !== nodeId)
  if (selectedNodeId.value === nodeId) {
    selectedNodeId.value = null
  }
  addLog(`Deleted node: ${nodeId}`, 'info')
}

const handleUpdateNodeConfig = (nodeId: string, key: string, value: unknown) => {
  const node = nodes.value.find(n => n.id === nodeId)
  if (node) {
    node.data.configValues[key] = value
    addLog(`Updated ${node.data.name}: ${key} = ${value}`, 'debug')
  }
}

const handleConnect = (connection: { source: string; target: string }) => {
  const id = `edge_${Date.now()}`
  edges.value.push({
    id,
    source: connection.source,
    target: connection.target
  })
  addLog(`Connected ${connection.source} -> ${connection.target}`, 'info')
}

provide('deleteNode', handleDeleteNode)

const handleSave = async () => {
  showSaveDialog.value = true
}

const handleSaveConfirm = async (name: string) => {
  showSaveDialog.value = false
  currentWorkflow.value = name
  const workflow = {
    name: currentWorkflow.value,
    version: '1.0',
    nodes: nodes.value.map(n => ({
      id: n.id,
      type: n.data.id || n.type,
      name: n.data.name,
      icon: n.data.icon,
      category: n.data.category,
      position: n.position,
      config: n.data.config,
      inputs: n.data.inputs,
      outputs: n.data.outputs,
      configValues: n.data.configValues
    })),
    edges: edges.value.map(e => ({
      id: e.id,
      source: e.source,
      target: e.target,
      sourceHandle: e.sourceHandle || '',
      targetHandle: e.targetHandle || ''
    }))
  }
  try {
    await saveWorkflow(currentWorkflow.value, workflow as any)
    addLog(`Saved workflow: ${currentWorkflow.value}`, 'info')
    const workflows = await listWorkflows()
    workflowList.value = workflows
  } catch (e) {
    addLog(`Failed to save: ${e instanceof Error ? e.message : 'Unknown error'}`, 'error')
  }
}

const handleSaveCancel = () => {
  showSaveDialog.value = false
}

const handleLoad = async (name: string) => {
  try {
    const workflow = await loadWorkflowApi(name)
    currentWorkflow.value = name

    const loadedNodes = workflow.nodes.map((n: any) => {
      const configValues = n.configValues || {}
      const plugin = plugins.value.find(p => p.id === n.type || p.name === n.name)
      return {
        id: n.id,
        type: 'dynamic',
        position: n.position || { x: 0, y: 0 },
        data: {
          id: n.id,
          name: n.name,
          icon: n.icon || (plugin?.icon || '📦'),
          category: n.category || (plugin?.category || ''),
          type: n.type,
          config: n.config || (plugin?.config || []),
          inputs: n.inputs || (plugin?.inputs || []),
          outputs: n.outputs || (plugin?.outputs || []),
          configValues: configValues
        }
      }
    })

    const loadedEdges = (workflow.edges || []).map((e: any) => ({
      id: e.id || `edge_${Date.now()}`,
      source: e.source,
      target: e.target,
      sourceHandle: e.sourceHandle || null,
      targetHandle: e.targetHandle || null
    }))

    nodes.value = loadedNodes
    edges.value = loadedEdges
    addLog(`Loaded workflow: ${name}`, 'info')
  } catch (e) {
    addLog(`Failed to load: ${e instanceof Error ? e.message : 'Unknown error'}`, 'error')
  }
}

const handleNew = () => {
  currentWorkflow.value = null
  nodes.value = []
  edges.value = []
  addLog('Created new workflow', 'info')
}

const handleLoadData = async () => {
  try {
    const [nodesData, categoriesData, workflows] = await Promise.all([
      getNodes(),
      getCategories(),
      listWorkflows()
    ])
    plugins.value = nodesData
    categories.value = categoriesData
    workflowList.value = workflows
    addLog(`Loaded ${nodesData.length} nodes and ${workflows.length} workflows`, 'info')
  } catch (e) {
    addLog(`Failed to load data: ${e instanceof Error ? e.message : 'Unknown error'}`, 'error')
  }
}

onMounted(() => {
  handleLoadData()
})

let ws: WebSocket | null = null

const connectWebSocket = (taskId: string) => {
  if (ws) {
    ws.close()
  }
  const wsUrl = `ws://localhost:8000/ws/execute/${taskId}`
  ws = new WebSocket(wsUrl)

  ws.onopen = () => {
    addLog(`WebSocket connected: ${taskId}`, 'info')
  }

  ws.onmessage = (event) => {
    try {
      const data = JSON.parse(event.data)
      if (data.type === 'log') {
        addLog(data.message, data.level as any, 'BE')
      } else if (data.type === 'status') {
        if (data.status === 'completed') {
          addLog(`Execution completed`, 'info')
        } else if (data.status === 'failed') {
          addLog(`Execution failed: ${data.error}`, 'error')
        }
        ws?.close()
        ws = null
      }
    } catch (e) {
      console.error('WebSocket message parse error:', e)
    }
  }

  ws.onerror = (error) => {
    addLog(`WebSocket error`, 'error')
    console.error('WebSocket error:', error)
  }

  ws.onclose = () => {
    ws = null
  }
}

const handleExecute = async () => {
  if (!currentWorkflow.value) {
    addLog('No workflow to execute', 'warn')
    return
  }
  if (nodes.value.length === 0) {
    addLog('No nodes to execute', 'warn')
    return
  }
  try {
    addLog('Starting workflow execution...', 'info')
    const workflowData = {
      name: currentWorkflow.value,
      version: '1.0',
      nodes: nodes.value.map(n => ({
        id: n.id,
        type: n.type,
        name: n.data.name,
        configValues: n.data.configValues,
        position: n.position
      })),
      edges: edges.value.map(e => ({
        id: e.id,
        source: e.source,
        target: e.target
      }))
    }
    const result = await executeWorkflow(workflowData as any)
    currentTaskId.value = result.taskId
    addLog(`Execution started: ${result.taskId}`, 'info')
    connectWebSocket(result.taskId)
  } catch (e) {
    addLog(`Failed to execute: ${e instanceof Error ? e.message : 'Unknown error'}`, 'error')
  }
}

const handleStop = () => {
  if (ws) {
    ws.close()
    ws = null
  }
  currentTaskId.value = null
  addLog('Execution stopped', 'warn')
}
</script>

<template>
  <div class="app-container">
    <TopToolbar
      :workflowName="currentWorkflow"
      :workflowList="workflowList"
      @save="handleSave"
      @load="handleLoad"
      @execute="handleExecute"
      @stop="handleStop"
      @new="handleNew"
    />
    <div class="main-content">
      <FileList
        :workflowList="workflowList"
        :activeWorkflow="currentWorkflow"
        @select="handleLoad"
        @refresh="handleLoadData"
      />
      <div class="canvas-area">
        <FloatingToolbar :plugins="plugins" :categories="categories" />
        <WorkflowCanvas
          :nodes="nodes"
          :edges="edges"
          :selectedNodeId="selectedNodeId"
          @add-node="handleAddNode"
          @select-node="handleSelectNode"
          @delete-node="handleDeleteNode"
          @update-node-config="handleUpdateNodeConfig"
          @connect="handleConnect"
        />
        <BottomPanel :logs="logs" @clear="clearLogs" />
      </div>
    </div>
    <SaveDialog
      :visible="showSaveDialog"
      :initialName="currentWorkflow || ''"
      @confirm="handleSaveConfirm"
      @cancel="handleSaveCancel"
    />
  </div>
</template>

<style scoped>
.app-container {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background: var(--bg-primary);
  color: var(--text-primary);
}

.main-content {
  flex: 1;
  display: flex;
  overflow: hidden;
}

.canvas-area {
  flex: 1;
  display: flex;
  flex-direction: column;
  position: relative;
  overflow: hidden;
}
</style>

// frontend/src/App.tsx
import { useEffect, useState, useCallback } from 'react';
import { ReactFlowProvider } from '@xyflow/react';
import { getNodes, listWorkflows } from './services/api';
import { useWorkflowTabs } from './hooks/useWorkflowTabs';
import { useResize } from './hooks/useResize';
import { Toolbox } from './components/Toolbox';
import { WorkflowCanvas } from './components/WorkflowCanvas';
import { ConfigPanel } from './components/ConfigPanel';
import { TopToolbar } from './components/TopToolbar';
import { StatusBar } from './components/StatusBar';
import { BottomPanel } from './components/BottomPanel';
import { WorkflowTabs } from './components/WorkflowTabs';
import { Layout } from './components/Layout';
import type { LogEntry } from './components/BottomPanel';
import type { PluginDefinition, EdgeData } from './types/api';
import logger from './utils/logger';

function WorkflowApp() {
  const [plugins, setPlugins] = useState<PluginDefinition[]>([]);
  const [workflowList, setWorkflowList] = useState<string[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [logs, setLogs] = useState<LogEntry[]>([]);

  const toolboxResize = useResize({
    minSize: 150,
    maxSize: 400,
    initialSize: 220,
    direction: 'horizontal',
  });

  const configPanelResize = useResize({
    minSize: 200,
    maxSize: 500,
    initialSize: 300,
    direction: 'horizontal',
  });

  const bottomPanelResize = useResize({
    minSize: 80,
    maxSize: 400,
    initialSize: 150,
    direction: 'vertical',
  });

  const {
    tabs,
    activeTabId,
    activeWorkflow,
    activeSelectedNode,
    createNewTab,
    openTab,
    closeTab,
    selectTab,
    renameTab,
    renameTabByName,
    saveWorkflow,
    executeWorkflow,
    stopExecution,
    selectNode,
    updateNodeConfig,
    addNode,
    removeNode,
    updateNodePosition,
    addEdge,
    removeEdge,
    setOnSaveCallback,
    setOnRenameCallback,
  } = useWorkflowTabs();

  const addLog = useCallback((
    message: string,
    level: 'debug' | 'info' | 'warn' | 'error',
    source: 'FE' | 'BE' = 'FE'
  ) => {
    const entry: LogEntry = {
      id: `${Date.now()}_${Math.random().toString(36).slice(2, 11)}`,
      timestamp: new Date().toLocaleTimeString('zh-CN', {
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: false,
      }),
      source,
      level,
      message,
    };
    setLogs(prev => [...prev, entry]);

    if (source === 'FE') {
      switch (level) {
        case 'debug': logger.debug(message); break;
        case 'info': logger.info(message); break;
        case 'warn': logger.warn(message); break;
        case 'error': logger.error(message); break;
      }
    }
  }, []);

  const clearLogs = useCallback(() => {
    setLogs([]);
  }, []);

  useEffect(() => {
    getNodes()
      .then(setPlugins)
      .catch((e) => {
        setError(e.message);
        addLog(`Failed to load plugins: ${e.message}`, 'error', 'FE');
      });
    listWorkflows()
      .then(setWorkflowList)
      .catch((e) => {
        setError(e.message);
        addLog(`Failed to load workflows: ${e.message}`, 'error', 'FE');
      });

    addLog('Application started', 'info', 'FE');
  }, [addLog]);

  useEffect(() => {
    setOnRenameCallback((oldName, newName) => {
      listWorkflows().then(setWorkflowList);
    });
  }, [setOnRenameCallback]);

  const handleSave = useCallback(() => {
    saveWorkflow().then(() => {
      listWorkflows().then(setWorkflowList);
      addLog(`Workflow saved: ${activeWorkflow?.name}`, 'info', 'FE');
    });
  }, [saveWorkflow, activeWorkflow?.name, addLog]);

  const handleEdgesChange = useCallback(
    (changes: unknown[]) => {
      for (const change of changes as { type: string; edge?: EdgeData; id?: string }[]) {
        if (change.type === 'add' && change.edge) {
          addEdge(change.edge);
        } else if (change.type === 'remove' && change.id) {
          removeEdge(change.id);
        }
      }
    },
    [addEdge, removeEdge]
  );

  const handleLoad = useCallback(
    (name: string) => {
      if (name) {
        openTab(name);
        addLog(`Workflow opened: ${name}`, 'info', 'FE');
      }
    },
    [openTab, addLog]
  );

  const handleRenameWorkflow = useCallback(
    (oldName: string, newName: string) => {
      renameTabByName(oldName, newName);
      listWorkflows().then(setWorkflowList);
    },
    [renameTabByName]
  );

  const handleNew = useCallback(() => {
    createNewTab();
    addLog('New workflow tab created', 'info', 'FE');
  }, [createNewTab, addLog]);

  const handleAddNode = useCallback(
    (node: { data: unknown; position: { x: number; y: number }; id: string }) => {
      addNode(node.data as unknown as PluginDefinition, node.position, node.id);
      addLog(`Node added: ${node.data && (node.data as { name?: string }).name || node.id}`, 'info', 'FE');
    },
    [addNode, addLog]
  );

  const handleTabClose = useCallback((tabId: string) => {
    const tab = tabs.find(t => t.id === tabId);
    if (tab?.isDirty) {
      if (!confirm(`"${tab.name}" 有未保存的更改，确定要关闭吗？`)) {
        return;
      }
    }
    closeTab(tabId);
  }, [tabs, closeTab]);

  const activeTab = tabs.find(t => t.id === activeTabId);

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        height: '100vh',
        background: 'var(--bg-primary)',
        color: 'var(--text-primary)',
      }}
    >
      <TopToolbar
        workflowName={activeWorkflow?.name || ''}
        workflowList={workflowList}
        executionState={activeTab?.executionState || null}
        isLoading={activeTab?.isLoading || false}
        onSave={handleSave}
        onLoad={handleLoad}
        onExecute={executeWorkflow}
        onStop={stopExecution}
        onNew={handleNew}
      />

      <Layout
        toolbox={<Toolbox plugins={plugins} workflowList={workflowList} onLoadWorkflow={handleLoad} onWorkflowListChange={() => listWorkflows().then(setWorkflowList)} onRenameWorkflow={handleRenameWorkflow} />}
        configPanel={
          <ConfigPanel
            node={activeSelectedNode}
            onUpdateConfig={(cv) => {
              if (activeSelectedNode) {
                updateNodeConfig(activeSelectedNode.id, cv);
              }
            }}
          />
        }
        canvas={
          activeWorkflow ? (
            <WorkflowCanvas
              nodes={activeWorkflow.nodes}
              edges={activeWorkflow.edges}
              selectedNodeId={activeTab?.selectedNodeId ?? null}
              onEdgesChange={handleEdgesChange}
              onSelectNode={selectNode}
              onAddNode={handleAddNode}
              onPositionChange={updateNodePosition}
              onDeleteNode={removeNode}
              onDeleteEdge={removeEdge}
              onEdgeAdd={addEdge}
              onSave={handleSave}
              plugins={plugins}
            />
          ) : (
            <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#6b7280' }}>
              <div style={{ textAlign: 'center' }}>
                <div style={{ fontSize: 48, marginBottom: 16 }}>📋</div>
                <div style={{ fontSize: 16 }}>点击「新建」开始设计工作流</div>
              </div>
            </div>
          )
        }
        bottomPanel={<BottomPanel logs={logs} onClearLogs={clearLogs} />}
        toolboxResize={toolboxResize}
        configPanelResize={configPanelResize}
        bottomPanelResize={bottomPanelResize}
        tabBar={tabs.length > 0 ? (
          <WorkflowTabs
            tabs={tabs.map(t => ({ id: t.id, name: t.name, isDirty: t.isDirty }))}
            activeTabId={activeTabId}
            onTabSelect={selectTab}
            onTabClose={handleTabClose}
            onTabRename={renameTab}
          />
        ) : null}
      />

      <StatusBar
        executionState={activeTab?.executionState || null}
        error={activeTab?.error || error}
        onDismissError={() => setError(null)}
      />
    </div>
  );
}

function App() {
  return (
    <ReactFlowProvider>
      <WorkflowApp />
    </ReactFlowProvider>
  );
}

export default App;
